apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: coreos-updatenotice
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: ClusterFirst
          containers:
          - name: coreos-updatenotice
            image: slintes/coreos-updatenotice
            env:
              - name: COREOS_CHANNELS
                value: stable,beta
              - name: WEBHOOK_KEY
                value: COREOS_VERSION
              - name: WEBHOOK_URL
                valueFrom:
                  configMapKeyRef:
                    name: coreos-updatenotice
                    key: webhook_url
              - name: REDIS_HOST
                value: redis
              - name: REDIS_PORT
                value: "6379"
          restartPolicy: OnFailure
